/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../ses-next/src/sanity/schema.json
export type Training = {
  _id: string;
  _type: 'training';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  trainingTitle?: string;
  icon?:
    | 'air'
    | 'facebook'
    | 'height'
    | 'light'
    | 'bolt'
    | 'linked-in'
    | 'mobile'
    | 'plug'
    | 'phone'
    | 'power'
    | 'recycle'
    | 'space'
    | 'tick-circle'
    | 'signal-tower'
    | 'wrench'
    | 'warning'
    | 'x'
    | 'bars-staggered';
};

export type TermsAndConditions = {
  _id: string;
  _type: 'terms-and-conditions';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  terms?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type TeamMember = {
  _id: string;
  _type: 'teamMember';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companyName?: string;
  alternateName?: string;
  companyLogo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  shortTitle?: string;
  baseUrl?: string;
  phone?: string;
  mobile?: string;
  email?: string;
  address?: string;
  abn?: string;
  recLicence?: string;
  businessHours?: string;
  establishedYear?: number;
  directorName?: string;
  latitude?: number;
  longitude?: number;
  streetAddress?: string;
  suburb?: string;
  state?: string;
  postcode?: string;
  openingHours?: {
    daysOfWeek?: Array<string>;
    opensAt?: string;
    closesAt?: string;
  };
  owner?: {
    name?: string;
    role?: string;
    accreditations?: Array<string>;
  };
  googleMapsLocation?: string;
  googleMapsLocationPlaceUrl?: string;
  meta?: {
    title?: string;
    description?: string;
  };
  socialMedia?: {
    facebook?: string;
    linkedIn?: string;
    instagram?: string;
  };
};

export type ServicesHub = {
  _id: string;
  _type: 'servicesHub';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  pageTitle?: string;
  pageDescription?: string;
  heading?: string;
  intro?: Array<string>;
};

export type ShowcaseReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'showcase';
};

export type ServiceReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'service';
};

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  description?: string;
  seoTitle?: string;
  seoDescription?: string;
  serviceType?: string;
  blurb?: string;
  slug?: Slug;
  linkToReadMore?: boolean;
  showOnHomepage?: boolean;
  icon?:
    | 'air'
    | 'facebook'
    | 'height'
    | 'light'
    | 'bolt'
    | 'linked-in'
    | 'mobile'
    | 'plug'
    | 'phone'
    | 'power'
    | 'recycle'
    | 'space'
    | 'tick-circle'
    | 'signal-tower'
    | 'wrench'
    | 'warning'
    | 'x'
    | 'bars-staggered';
  showcase?: Array<
    {
      _key: string;
    } & ShowcaseReference
  >;
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  parentService?: ServiceReference;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Showcase = {
  _id: string;
  _type: 'showcase';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  featured?: boolean;
};

export type LocationPageReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'locationPage';
};

export type LocationPage = {
  _id: string;
  _type: 'locationPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  suburb?: string;
  slug?: Slug;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: 'image';
        _key: string;
      }
  >;
  services?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  nearbySuburbs?: Array<
    {
      _key: string;
    } & LocationPageReference
  >;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  seoTitle?: string;
  seoDescription?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'teamMember';
};

export type TrainingReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'training';
};

export type Homepage = {
  _id: string;
  _type: 'homepage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  mainHeading?: string;
  subHeading?: string;
  about?: Array<string>;
  contact?: {
    blurbs?: Array<string>;
    callBack?: string;
    phone?: string;
  };
  services?: {
    blurbs?: Array<string>;
    items?: Array<
      {
        _key: string;
      } & ServiceReference
    >;
  };
  team?: {
    blurbs?: Array<string>;
    members?: Array<
      {
        _key: string;
      } & TeamMemberReference
    >;
  };
  training?: Array<
    {
      _key: string;
    } & TrainingReference
  >;
  trustSignals?: Array<{
    value?: string;
    label?: string;
    icon?: string;
    _key: string;
  }>;
  serviceAreas?: Array<
    {
      _key: string;
    } & LocationPageReference
  >;
};

export type Faq = {
  _id: string;
  _type: 'faq';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: string;
};

export type BlogPost = {
  _id: string;
  _type: 'blog-post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  slug?: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  publishedAt?: string;
  tags?: Array<string>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Training
  | TermsAndConditions
  | SanityImageAssetReference
  | TeamMember
  | SanityImageCrop
  | SanityImageHotspot
  | SiteSettings
  | ServicesHub
  | ShowcaseReference
  | ServiceReference
  | Service
  | Slug
  | Showcase
  | LocationPageReference
  | LocationPage
  | TeamMemberReference
  | TrainingReference
  | Homepage
  | Faq
  | BlogPost
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
