import Head from 'next/head';

import Container from '../components/Container';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <div className="from-primary to-secondary text-primary-content -mt-[4rem] grid place-items-center items-end bg-gradient-to-br pt-20">
          <div className="hero-content col-start-1 row-start-1 w-full max-w-7xl flex-col justify-between gap-10 pb-40 lg:flex-row lg:items-end lg:gap-0 xl:gap-20">
            <div className="lg:pl-10 lg:pb-32">
              <Container>
                <div className="mb-2 py-4 text-center lg:py-10 lg:text-left">
                  <h1 className="font-title mb-2 text-xl font-extrabold sm:text-5xl lg:text-7xl">
                    Storm Electrical Solutions
                  </h1>
                  <h2 className="font-title text-lg font-extrabold sm:text-2xl lg:text-3xl">
                    The most popular, free and open-source <br />
                    Tailwind CSS component library
                  </h2>
                </div>
              </Container>
            </div>
          </div>
        </div>
      </main>

      <footer>Footer goes here</footer>
    </>
  );
}
