export { About } from './About';
export { Contact } from './Contact';
export { Container } from './Container';
export { FeedbackForm } from './FeedbackForm';
export { Icon } from './Icon/Icon';
export { Footer } from './Footer';
export { Gallery } from './Gallery';
export { GalleryCarousel } from './GalleryCarousel';
export { HeroV1, HeroV2 } from './Hero';
export { Modal } from './Modal';
export { Navbar } from './Navbar';
export { PopSuccess } from './PopSuccess';
export { ServicesV1, ServicesV2 } from './Services';
export { Team } from './Team';
